apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.appName }}-route
  namespace: {{ .Values.nameSpace }}
spec:
  parentRefs:
    - name: {{ .Values.httproute.gatewayName }}
      namespace: {{ .Values.httproute.gatewayNameSpace }}
  {{- with .Values.httproute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: {{ .Values.httproute.rules.pathType }}
            value: {{ .Values.httproute.rules.pathValue }}
      backendRefs:
        - name: {{ .Values.appName }}
          port: {{ .Values.service.port }}