apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clsIssuer.secName }}
  namespace: {{ .Values.clsIssuer.tls.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.clsIssuer.tls.crt }}
  tls.key: {{ .Values.clsIssuer.tls.key }}


