apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.gateway.certificate.name }}
  namespace: {{ .Values.gateway.nameSpace }}
spec:
  secretName: {{ .Values.gateway.certificate.secName }}
  duration: {{ .Values.gateway.certificate.duration }}
  renewBefore: {{ .Values.gateway.certificate.renewBefore }}
  subject:
    organizations:
      - {{ .Values.gateway.certificate.org1 }}
  commonName: {{ .Values.gateway.certificate.cName }}
  issuerRef:
    name: {{ .Values.sslcertificate.clsIssuer.name }}
    kind: ClusterIssuer
    group: cert-manager.io