apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcVolume.name }}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.appName }}
spec:
  accessModes:
    - {{ .Values.pvcVolume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvcVolume.storageSize }}
  storageClassName: {{ .Values.pvcVolume.storageClassName }}
