apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.sslcertificate.gateway.name }}
  namespace: {{ .Values.sslcertificate.gateway.nameSpace }}
spec:
  gatewayClassName: {{ .Values.sslcertificate.gateway.class }}
  listeners:
    - name: {{ .Values.sslcertificate.gateway.listeners.name1 }}
      protocol: {{ .Values.sslcertificate.gateway.listeners.protocol1 }}
      port: {{ .Values.sslcertificate.gateway.listeners.port1 }}
      allowedRoutes:
        namespaces:
          from: {{ .Values.sslcertificate.gateway.listeners.allowedRoutes.from }}
    - name: {{ .Values.sslcertificate.gateway.listeners.name2 }}
      protocol: {{ .Values.sslcertificate.gateway.listeners.protocol2 }}
      port: {{ .Values.sslcertificate.gateway.listeners.port2 }}
      tls:
        certificateRefs:
          - kind: Secret
            name: {{ .Values.sslcertificate.gateway.certificate.secName }}
        mode: {{ .Values.sslcertificate.clsIssuer.tls.mode }}
      allowedRoutes:
        namespaces:
          from: {{ .Values.sslcertificate.gateway.listeners.allowedRoutes.from }}