appName: vproapp
replicaCount: 1
nameSpace: astrix
image:
  repository: lalitt76/vprofile-app
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: v1
service:
  type: ClusterIP
  port: 8080
httproute:
  gatewayName: vpro-gateway
  gatewayNameSpace: projectcontour
  hostnames:
    - vprofile.thetyagi.com
  rules:
    pathType: PathPrefix
    pathValue: /
initContainers:
  - name: init-mydb
    image: busybox:latest
    command: ['sh', '-c', 'until nslookup vprodb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
  - name: init-memcache
    image: busybox:latest
    command: ['sh', '-c', 'until nslookup vprormq.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for vprormq; sleep 2; done;']
  - name: init-rabbitmq
    image: busybox:latest
    command: ['sh', '-c', 'until nslookup vpromc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for vprormq; sleep 2; done;']