apiVersion: v2
name: vproapp
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: vprodb
    version: 0.2.0
    repository: "file://./charts/vprodb"
    enabled: true
  - name: vpromc
    version: 0.1.0
    repository: "file://./charts/vpromc"
    enabled: true
  - name: vprormq
    version: 0.1.0
    repository: "file://./charts/vprormq"
    enabled: true


