# Default values for vprormq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appName: vprormq
nameSpace: astrix
replicaCount: 1

service:
  type: ClusterIP
  port: 15672

image:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  tag: latest

secret:
  key: rmqpass
  value: Z3Vlc3Q=